### ISSUE TITLE
BottomSheet content does not update after initial render

### ISSUE THREAD

**Issue by emilsjolander** [adamfootdev/BottomSheet#10]
Hey there! I'm having an issue where the contents of the bottom sheet does not change after initial render even though the content view build is re-run and returns a new view.

My code looks something like the following:
```swift
.bottomSheet(item: self.$selectedItem, detents: [.medium()], prefersGrabberVisible: true) {
    if let item = self.selectedItem {
        Text("Item: \(item.title)")
    } else {
        Text("No item selected").
    }
}
```

When initially rendering this the view which has the `bottomSheet` modifier, `self.$selectedItem` is nil and thus the bottom sheet is not presented but the content view builder is invoked. This is expected. The initial render will produce the "No item selected" label.

When `self.$selectedItem` is updated to refer to a selected item I want the bottom sheet to be presented and display the item's title. What happens instead is that the bottom sheet is presented but displays "No item selected". Using breakpoints in Xcode I can confirm that the content view builder re-invoked when an item is selected and the correct branch of the if statement is invoked, so it *should* be displaying my item title. It seems that the hosting view controller is not updated with the new content view though.

**Comment by BrentMifsud** [comment]
I had a similar issue. I was trying to build a similar library to this, but I was adding the ability to programatically change the detent in swiftui.

Its as you said. It seems the UIHostingControllers are not updating their state.

I wonder if there is a way to hook into the default SwiftUI Sheet and use that to present these bottom sheets. As under the hood, it is using a UISheetPresentationController.
