### ISSUE TITLE
'shared' is unavailable in application extensions for iOS

### ISSUE THREAD

**Issue by lvandal** [adamfootdev/BottomSheet#3]
I'm trying to implement BottomSheet with Xcode 13 beta 3 and iOS 15 beta 3 but I get this compiler error:

'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.

Perhaps this has changed in a recent iOS 15 beta?

**Comment by lvandal** [comment]
What is odd is that I only get this error when I import BottomSheet as a package. If I download the source and use it directly, it works.

**Comment by lvandal** [comment]
Here's a sample project to reproduce the issue (Xcode 13 beta 3 13A5192i):

[BottomTest.zip](https://github.com/adamfootdev/BottomSheet/files/6823891/BottomTest.zip)

**Comment by Rspoon3** [comment]
I also have this issue on the same Xcode version.

**Comment by ay8s** [comment]
Related to https://twitter.com/twannl/status/1415643862761152513

**Comment by Rspoon3** [comment]
I came across that too. If you inject the UIApplication into the class it works. I [created a pull request](https://github.com/adamfootdev/BottomSheet/pull/6) for this.

**Comment by adamfootdev** [comment]
This issue should now be fixed in release 0.2
