### ISSUE TITLE
No sheet appearing when isPresented is initially true

### ISSUE THREAD

**Issue by ralfebert** [adamfootdev/BottomSheet#8]
No sheet appears for this example (0.2.2, Simulator in Xcode 13 Beta 5):

```swift
import SwiftUI
import BottomSheet

struct ContentView: View {
    @State private var bottomSheetPresented = true
    
    var body: some View {
        Color.yellow
            .ignoresSafeArea()
            .bottomSheet(isPresented: $bottomSheetPresented) {
                Text("Hello, world!")
            }
    }
}
```

The interactive version works:

```swift
struct ContentView: View {
    @State private var bottomSheetPresented = false
    
    var body: some View {
        VStack {
            Button("Show Sheet") {
                bottomSheetPresented = true
            }
        }
        .bottomSheet(isPresented: $bottomSheetPresented) {
            Text("Hello, world!")
        }
    }
}
```

Is there a way to get a sheet that's permanently visible / is it supposed to work with `isPresented == true` initially?

**Comment by ralfebert** [comment]
Ah, the interactive version works:

```swift
struct ContentView: View {
    @State private var bottomSheetPresented = false
    
    var body: some View {
        VStack {
            Button("Show Sheet") {
                bottomSheetPresented = true
            }
        }
            .ignoresSafeArea()
            .bottomSheet(isPresented: $bottomSheetPresented, detents: [.medium(), .large()]) {
                Text("Hello, world!")
            }
    }
}
```

Is there a way to get a sheet that's permanently visible / is it supposed to work with `isPresented == true` initially?

**Comment by adamfootdev** [comment]
I imagine it's because it's trying to show a UIKit sheet straight away as it's a bit of a hack as opposed to a native SwiftUI view.

I'll take a look to see if there's anything I can do to make it work better, but have you tried toggling the state property to true in onAppear?

**Comment by ralfebert** [comment]
Unfortunately, onAppear as workaround doesn't work. Currently just playing around and wanted to to report it, I am not sure how realistic UISheetPresentationController is as "always visible" part of the UI, seems to be more tailored for temporary sheets.

**Comment by MarcoMartignone** [comment]
```
struct ContentView: View {
    @State private var bottomSheetPresented = false
    
    var body: some View {
        Color.purple
        .bottomSheet(isPresented: $bottomSheetPresented) {
            Text("Hello, world!")
        }
        
        .onAppear(perform: presentSheet)
    }
    
    private func presentSheet() {
        DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
            bottomSheetPresented = true
        }
    }
}
```
Adding some delay to the present function called on onApper fixes the issue!

**Comment by adamfootdev** [comment]
It probably doesn't work straight away as it's requesting a sheet to appear from UIKit and there's probably a very slight delay until that happens.

By adding a delay to the State property being changed as suggested, will probably be the only way to get it to work reliably until Apple brings out their own solution!
