### ISSUE TITLE
Project won't compile after installing the package

### ISSUE THREAD

**Issue by NaifAlrashed** [adamfootdev/BottomSheet#9]
after installing the library, I get this error:
<img width="1401" alt="Screen Shot 2021-09-10 at 7 57 59 AM" src="https://user-images.githubusercontent.com/15128710/132801901-2cd34078-5803-4979-92b7-6b309a47d607.png">

I think this thread will help a lot in fixing this issue:
https://twitter.com/twannl/status/1415643862761152513

**Comment by adamfootdev** [comment]
Have you tried running this on Xcode 13 beta 5? Beta 3 & 4 broke this functionality and I added a workaround as a result but it should now work fine in beta 5.
